CREATE DATABASE ENCUESTADOR_ITLA
GO;
USE ENCUESTADOR_ITLA
GO;

CREATE TABLE USERS(
ID_USER INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL
)
GO

CREATE TABLE QUIZ(
ID_QUIZ INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL
)
GO

CREATE TABLE QUESTIONS(
ID_QUESTION INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_QUIZ INT FOREIGN KEY REFERENCES QUIZ(ID_QUIZ) ON DELETE CASCADE NOT NULL,
QUESTION VARCHAR(200) NOT NULL,
)
GO

CREATE TABLE ANSWERS(
ID_ANSWER INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
ID_QUESTION INT FOREIGN KEY REFERENCES QUESTIONS(ID_QUESTION) ON DELETE CASCADE NOT NULL,
NAME_PERSON VARCHAR(50) NOT NULL,
ID_USER INT FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
ANSWER VARCHAR(500) NOT NULL
)
GO